### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by VB10** [HalukHackali/dindefterim_mobil_app#4]
https://github.com/HalukHackali/dindefterim_mobil_app/blob/3920d9009603e7ff8089a09cbd9ba02da36b26da/lib/features/okul/model/kademeler/lise/lise_ekranlari.dart#L156

theme.of(context).color

**Comment by HalukHackali** [comment]
`color: Theme.of(context).colorScheme.onSecondary,`

kullanıldı.
